apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-session-server-deployment
  labels:
    app: otus-session-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otus-session-server
  template:
    metadata:
      labels:
        app: otus-session-server
    spec:
      containers:
      - name: otus-session-server
        image: arsenteroganisyan/otus-session-server:v1
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: port